# Model architecture
model:
  input_size: 16000  # Audio input length
  wavelet_channels: 16  # Number of wavelet transform channels
  hidden_channels: 32  # Number of feature extraction channels
  bottleneck_channels: 256  # Number of bottleneck channels
  wavelet_type: "morlet"  # Options: morlet, mexican_hat, learnable
  wavelet_mlp_layers: [1, 32, 64, 32]  # Wavelet parameter network layers

# Training parameters
training:
  batch_size: 8
  learning_rate: 0.0003
  max_epochs: 50
  gradient_accumulation: 1
  num_workers: 4

# Data parameters
data:
  train_path: "data/train"
  val_path: "data/val"
  sample_rate: 16000
  
# Logging
logging:
  tensorboard_dir: "logs"
  log_every_n_steps: 10
  save_checkpoint_every_n_epochs: 5