# General parameters
model_name: "wst_complex_autoencoder"
seed: 42
output_dir: "./logs"

# Data parameters
data:
  sample_rate: 16000
  audio_length: 2.0  # in seconds
  hop_length: 256
  n_fft: 1024
  n_mels: 80
  cache_size: 100  # Number of samples to cache in memory

# Wavelet Scattering Transform parameters
wavelet:
  J: 3  # Changed from 1 to 3 for better frequency resolution
  Q: 12  # Increased frequency resolution
  T: 8192  # Temporal support of the lowpass filter
  ensure_output_dim: true
  
# Model architecture
model:
  latent_dim: 256
  channels: [32, 64, 128, 256]
  kernel_sizes: [5, 5, 5, 5]
  strides: [2, 2, 2, 2]  # Back to standard strides
  paddings: [2, 2, 2, 2]
  output_paddings: [1, 1, 1, 1]  # Updated for standard strides
  dropout: 0.1
  use_batch_norm: true
  complex_repr: "rectangular"

# Training parameters
training:
  batch_size: 16
  accumulate_grad_batches: 2
  max_epochs: 100
  lr: 0.0002
  beta1: 0.5
  beta2: 0.999
  scheduler_gamma: 0.95
  num_workers: 4
  precision: 16-mixed

# Loss weights
loss:
  l1_weight: 1.0
  stft_weight: 1.0
  complex_loss_weight: 0.5  # Increased from 0.25 to 0.5 to emphasize phase
  spectral_convergence_weight: 0.5