# General parameters
model_name: "wst_complex_autoencoder"
seed: 42
output_dir: "./logs"

# Data parameters
data:
  sample_rate: 16000
  audio_length: 2.0  # in seconds
  hop_length: 256
  n_fft: 1024
  n_mels: 80
  cache_size: 100  # Number of samples to cache in memory

# Wavelet Scattering Transform parameters
wavelet:
  J: 8  # Number of scales
  Q: 8  # Number of wavelets per octave
  T: 8192  # Temporal support of the lowpass filter
  
# Model architecture
model:
  latent_dim: 128
  channels: [32, 64, 128, 256]
  kernel_sizes: [7, 5, 3, 3]
  strides: [2, 2, 2, 2]
  dropout: 0.1
  use_batch_norm: true
  complex_repr: "rectangular"  # rectangular or polar

# Training parameters
training:
  batch_size: 16
  accumulate_grad_batches: 2
  max_epochs: 100
  lr: 0.0002
  beta1: 0.5
  beta2: 0.999
  scheduler_gamma: 0.95
  num_workers: 4
  precision: 16-mixed  # Use mixed precision

# Loss weights
loss:
  l1_weight: 0.5
  stft_weight: 1.0
  complex_loss_weight: 0.25
  spectral_convergence_weight: 0.5